### ISSUE TITLE
Start up

### ISSUE THREAD

**Issue by smooJitter** [sammkj/meteor-1.3-todo#3]
How do you start this?

**Comment by kokjinsam** [comment]
What do you mean by that?

**Comment by smooJitter** [comment]
I'm sorry.  Lol.  I have had so many problems with Apollo kickstarts.  This installed like a charm

**Comment by smooJitter** [comment]
I do have a question a question about  configureGraphQLServer. 

On one hand, it looks like configureGraphQLServer is imported from apollo-tools.  On the other hand, I see the a configureGraphQLServer function is defined under config/configure-server.js but not imported.  Can you help me square this?

**Comment by kokjinsam** [comment]
I'm sorry. This repo is my apollo playground so it's kinda messy. I will try to clean it up this weekend. `configureGraphQLServer` from `apollo-tools` should do the same thing as the one under `config/configure-server.js`. I just put the code into a NPM package.

**Comment by smooJitter** [comment]
Although it says GraphQL Server  is running on http://localhost:4000

I can't get GraphiQL to run.

**Comment by kokjinsam** [comment]
You need to go `http://localhost:4000/graphql`. That's where you set your GraphiQL to be.

**Comment by veerjainATgmail** [comment]
Hi,

I am getting the following error. with http://localhost:3000/

Cannot read property 'allTodos' of undefined 
TypeError: Cannot read property 'allTodos' of undefined
    at http://localhost:3000/app/app.js?hash=d6a13cce114a77531a9c3292230f2dc67f46bdb0:464:32
    at http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:22

any work arounds?
1. can radium be disabled?

thanks a ton, 
veerjain

**Comment by veerjainATgmail** [comment]
guess seed is not working for me..

  "data": {
    "allTodos": null
  },
  "errors": [
    {
      "message": "regeneratorRuntime is not defined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}

**Comment by kokjinsam** [comment]
This repo is not updated to the newest version of Apollo. Probably that's causing the error

**Comment by kokjinsam** [comment]
Updated repo.
